<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function pokeapi_integration_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  
   if ($form_id == 'node_diary_edit_form' || $form_id == 'node_diary_form' ) {
  
    $form['field_pokemon_name']['widget'][0]['value']['#autocomplete_route_name'] = 'pokeapi_integration.autocomplete';
    $form['#attached']['library'][] = 'pokeapi_integration/pokeapi';
   }
}
